import {
  FaHome,
  FaSearch,
  FaPenSquare,
  FaUserAlt,
  FaBookmark,
  FaStar,
  FaRegStar,
  FaRegComment,
  FaRegHeart,
  FaRegBookmark,
  FaPen,
  FaEye,
  FaEyeSlash,
  FaSignInAlt,
  FaClipboardList,
  FaTimes,
  FaUser,
  FaHandHoldingHeart,
} from 'react-icons/fa'
import { FaGift, FaChevronRight, FaChevronLeft, FaChevronDown, FaChevronUp } from 'react-icons/fa6'

export const iconMapper = {
  FaHome,
  FaSearch,
  FaPenSquare,
  FaUserAlt,
  FaBookmark,
  FaRegBookmark,
  FaStar,
  FaRegStar,
  FaGift,
  FaRegComment,
  FaRegHeart,
  FaChevronRight,
  FaChevronLeft,
  FaChevronDown,
  FaChevronUp,
  FaPen,
  FaEye,
  FaEyeSlash,
  FaSignInAlt,
  FaClipboardList,
  FaTimes,
  FaUser,
  FaHandHoldingHeart,
}
