import {
  FaHome,
  FaSearch,
  FaPenSquare,
  FaUserAlt,
  FaBookmark,
  FaStar,
  FaRegStar,
  FaRegComment,
  FaRegHeart,
  FaRegBookmark,
  FaPen,
  FaEye,
  FaEyeSlash,
  FaSignInAlt,
  FaClipboardList,
  FaTimes,
} from 'react-icons/fa'
import { FaGift, FaChevronRight, FaChevronLeft } from 'react-icons/fa6'

export const iconMapper = {
  FaHome,
  FaSearch,
  FaPenSquare,
  FaUserAlt,
  FaBookmark,
  FaRegBookmark,
  FaStar,
  FaRegStar,
  FaGift,
  FaRegComment,
  FaRegHeart,
  FaChevronRight,
  FaChevronLeft,
  FaPen,
  FaEye,
  FaEyeSlash,
  FaSignInAlt,
  FaClipboardList,
  FaTimes,
}
