services:
  web:
    build:
      context: .
      dockerfile: "Dockerfile.prod"
    command: bash -c "bundle exec rails s -b '0.0.0.0'"
    volumes:
      - .:/myapp
    ports:
      - 3001:3000
    env_file:
      - .env
    tty: true
    stdin_open: true