services:
  web:
    build:
      context: .
      dockerfile: "Dockerfile.dev"
    command: bash -c "tail -f log/development.log"
    volumes:
      - .:/myapp
    ports:
      - 3001:3000
    env_file:
      - .env
    tty: true
    stdin_open: true
  redis:
    container_name: redis
    restart: always
    image: "redis:latest"
    ports:
    - "6379:6379"
    volumes:
    - "./data/redis:/data"