source "https://rubygems.org"

gem "rails", "~> 7.1"

gem "pg", "~> 1.1"

gem "puma", ">= 5.0"

gem "tzinfo-data", platforms: %i[ windows jruby ]

gem "bootsnap", require: false

# ▼CORS
gem "rack-cors"
# 環境ごとのドメイン設定管理を行う
gem "config"

# ▼キャッシュ
gem "redis"
gem "hiredis"

# ▼ユーザー認証
gem "devise"
# deviseの日本語化
gem "devise-i18n"
# トークン認証
gem "devise_token_auth"

group :development, :test do
  gem "debug", platforms: %i[ mri windows ], require: "debug/prelude"

  gem "brakeman", require: false

  gem "rubocop-rails-omakase", require: false

  gem "pry-byebug"
  gem "pry-doc"
  gem "pry-rails"

  gem "rspec-rails"

  # メール送受信のテスト
  gem "letter_opener_web"
end
