source "https://rubygems.org"

gem "rails", "~> 7.2.1"

gem "pg", "~> 1.1"

gem "puma", ">= 5.0"

gem "tzinfo-data", platforms: %i[ windows jruby ]

gem "bootsnap", require: false

gem "rack-cors"

gem "redis"
gem "hiredis"

group :development, :test do
  gem "debug", platforms: %i[ mri windows ], require: "debug/prelude"

  gem "brakeman", require: false

  gem "rubocop-rails-omakase", require: false

  gem "pry-byebug"
  gem "pry-doc"
  gem "pry-rails"

  gem "rspec-rails"
end
