source "https://rubygems.org"

gem "rails", "~> 7.1"

gem "pg", "~> 1.1"

gem "puma", ">= 5.0"

gem "tzinfo-data", platforms: %i[ windows jruby ]

gem "bootsnap", require: false

# ▼CORS
gem "rack-cors"
gem "config"  # 環境ごとのドメイン設定管理を行う

# ▼キャッシュ
gem "redis"
gem "hiredis"

# ▼ユーザー認証
gem "devise"
gem "devise-i18n" # deviseの日本語化
gem "devise_token_auth" # トークン認証

# ▼翻訳
gem "rails-i18n"

# ▼API
gem "alba"  # レスポンスJSONを制御する

# ▼モデルのネスト
gem "ancestry"

group :development, :test do
  gem "debug", platforms: %i[ mri windows ], require: "debug/prelude"

  gem "brakeman", require: false

  gem "rubocop-rails-omakase", require: false

  gem "pry-byebug"
  gem "pry-doc"
  gem "pry-rails"

  # ▼Rspec
  gem "rspec-rails"
  gem "factory_bot_rails" # テスト用データを作成する
  gem "faker"

  # ▼メール送受信のテスト
  gem "letter_opener_web"
end
